### ISSUE TITLE
Benefir from static analysis

### ISSUE THREAD

**Issue by szepeviktor** [imath/wp-statuses#38]
Please try running @phpstan on raising levels.

`phpstan.neon.dist`

```yaml
#$ composer require --dev szepeviktor/phpstan-wordpress
#$ vendor/bin/phpstan analyze -l 0

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - wp-statuses.php
        - inc/
    autoload_files:
        - wp-statuses.php
        - inc/core/functions.php
        - inc/core/custom.php
        - inc/core/classes/class-wp-statuses-core-status.php
        - inc/admin/classes/class-wp-statuses-admin.php
    dynamicConstantNames:
        - EMPTY_TRASH_DAYS
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$#'
        # TODO Define properties!
        - '#^Access to an undefined property WP_Statuses::\$[a-z_]+\.$#'
        # TODO Specify type hints!
        - '# has no return typehint specified\.$#'
        # It is a PHPStan bug.
        - '#^Parameter \#1 \$autoload_function of function spl_autoload_register expects callable\(string\): #'
    # TODO Remove!
    checkMissingIterableValueType: false
```
